let cruds = [], activeCrud = null, activeColumn = null, databaseAvailable = false, editingColumnId = null, editingOptionId = null;
const list = document.querySelector('#crudList'), status = document.querySelector('#databaseStatus');
const format = new Intl.NumberFormat('pt-BR');
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]);
const REQUEST_TIMEOUT_MS = 10000;
const request = async (path, options = {}) => {
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const response = await fetch(`api.php/${path}`, { cache: 'no-store', ...options, signal: controller.signal });
    const payload = response.status === 204 ? {} : await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(payload.error || `Erro na operação (HTTP ${response.status}).`);
    return payload;
  } catch (error) {
    if (error.name === 'AbortError') throw new Error('A conexão com o servidor demorou mais de 10 segundos.');
    throw error;
  } finally {
    window.clearTimeout(timeout);
  }
};

function updateStats() { document.querySelector('#crudCount').textContent = format.format(cruds.length); document.querySelector('#recordCount').textContent = format.format(cruds.reduce((n, c) => n + Number(c.records), 0)); document.querySelector('#columnCount').textContent = format.format(cruds.reduce((n, c) => n + Number(c.columns), 0)); }
function render(items = cruds) {
  updateStats();
  list.innerHTML = !items.length ? `<div class="col-span-full rounded-xl border border-dashed border-line bg-panel p-10 text-center"><p class="text-base font-semibold text-white">Nenhum CRUD encontrado</p><p class="mt-2 text-sm text-slate-500">Crie a primeira estrutura para ela aparecer aqui.</p></div>` : items.map(c => `<article class="rounded-xl border border-line bg-panel p-5 transition hover:border-violet hover:bg-slate-900"><div class="mb-6 flex justify-between"><div class="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-indigo-500 text-xl">${c.orientation ? '↕' : '↔'}</div><span class="text-xs text-slate-500">${c.columns} coluna(s)</span></div><h3 class="text-base font-semibold text-white">${escapeHtml(c.name)}</h3><div class="mt-2"><span class="rounded bg-slate-800 px-2 py-1 text-xs text-slate-400">${c.orientation ? 'Vertical' : 'Horizontal'}</span></div><div class="mt-6 grid grid-cols-2 border-t border-line pt-4 text-sm"><div><p class="text-xs text-slate-500">Colunas</p><p class="mt-1 font-semibold">${c.columns}</p></div><div class="border-l border-line pl-4"><p class="text-xs text-slate-500">Registros</p><p class="mt-1 font-semibold">${c.records}</p></div></div><div class="mt-5 grid grid-cols-2 gap-2"><button data-open="${c.id}" class="rounded-lg bg-violet px-3 py-2 text-sm font-semibold text-white hover:bg-violet-500">Abrir registros</button><button data-structure="${c.id}" class="rounded-lg border border-line px-3 py-2 text-sm font-semibold text-violet-200 hover:bg-violet/10">Colunas</button></div></article>`).join('');
  document.querySelectorAll('[data-open]').forEach(button => button.onclick = () => openCrud(button.dataset.open));
  document.querySelectorAll('[data-structure]').forEach(button => button.onclick = () => crudStructure(button.dataset.structure));
}
function setConnectionStatus(connected, detail = '') { databaseAvailable = connected; status.innerHTML = connected ? '<span class="h-2 w-2 rounded-full bg-emerald-400"></span> MySQL conectado' : `<span class="h-2 w-2 rounded-full bg-rose-400"></span> MySQL indisponível${detail ? `: ${escapeHtml(detail)}` : ''}`; document.querySelector('#newCrud').disabled = !connected; }
async function loadCruds() { try { await request('health'); const payload = await request('cruds'); cruds = payload.cruds.map(c => ({ ...c, orientation: +c.orientation, columns: +c.columns, records: +c.records })); setConnectionStatus(true); } catch (error) { cruds = []; setConnectionStatus(false, error.message); } render(); }
function showPage(id) { document.querySelector('#dashboard').classList.add('hidden'); document.querySelector('#recordsDetail').classList.add('hidden'); document.querySelector('#structureDetail').classList.add('hidden'); document.querySelector('#optionsDetail').classList.add('hidden'); document.querySelector(id).classList.remove('hidden'); }
function field(column, value = '') { const name = `value-${column.id}`; if (column.type === 2) return `<select name="${name}" class="input"><option value="">Selecione…</option>${column.options.map(o => `<option value="${o.id}" ${String(value) === String(o.id) ? 'selected' : ''}>${escapeHtml(o.value)}</option>`).join('')}</select>`; return `<input class="input" name="${name}" type="${column.type === 1 ? 'number' : 'text'}" value="${escapeHtml(value)}" />`; }
function recordSelect(column, value) { return `<select class="input mt-0 min-w-36"><option value="">Selecione…</option>${column.options.map(option => `<option value="${option.id}" ${String(value) === String(option.id) ? 'selected' : ''}>${escapeHtml(option.value)}</option>`).join('')}</select>`; }
function displayValue(column, value) { return column.type === 2 ? escapeHtml((column.options.find(o => String(o.id) === String(value)) || {}).value || '') : escapeHtml(value || ''); }
function editableRecordCell(column, record) { const value = record.values[column.id] ?? ''; return `<span data-editable-record="${record.id}" data-column="${column.id}" class="block min-h-5 cursor-text rounded px-1 -mx-1 hover:bg-slate-800/70" title="Dê dois cliques para editar">${displayValue(column, value)}</span>`; }
function renderRecords(c, columns) {
  if (!c.records.length) return `<tbody><tr><td colspan="${columns.length + 1}" class="p-7 text-center text-sm text-slate-500">Nenhum registro cadastrado.</td></tr></tbody>`;
  if (!c.orientation) { const head = columns.map(col => `<th class="px-4 py-3 text-left text-xs font-medium text-slate-400">${escapeHtml(col.name)}</th>`).join(''); const body = c.records.map(record => `<tr class="border-t border-line">${columns.map(col => `<td class="px-4 py-3 text-sm">${col.type === 0 || col.type === 2 ? editableRecordCell(col, record) : displayValue(col, record.values[col.id])}</td>`).join('')}<td class="whitespace-nowrap px-4 py-3"><button data-edit="${record.id}" class="text-sm text-violet-300">Editar</button><button data-delete-record="${record.id}" class="ml-3 text-sm text-rose-300">Excluir</button></td></tr>`).join(''); return `<thead><tr>${head}<th class="px-4 py-3"></th></tr></thead><tbody>${body}</tbody>`; }
  const head = c.records.map(record => `<th class="px-4 py-3 text-left text-xs font-medium text-slate-400">Registro #${record.id}</th>`).join(''); const body = columns.map(col => `<tr class="border-t border-line"><th class="px-4 py-3 text-left text-sm font-medium text-slate-300">${escapeHtml(col.name)}</th>${c.records.map(record => `<td class="px-4 py-3 text-sm">${col.type === 0 || col.type === 2 ? editableRecordCell(col, record) : displayValue(col, record.values[col.id])}</td>`).join('')}</tr>`).join(''); const actions = `<tr class="border-t border-line"><th class="px-4 py-3"></th>${c.records.map(record => `<td class="whitespace-nowrap px-4 py-3"><button data-edit="${record.id}" class="text-sm text-violet-300">Editar</button><button data-delete-record="${record.id}" class="ml-3 text-sm text-rose-300">Excluir</button></td>`).join('')}</tr>`; return `<thead><tr><th class="px-4 py-3"></th>${head}</tr></thead><tbody>${body}${actions}</tbody>`;
}
function renderRecordsDetail() { const c = activeCrud; showPage('#recordsDetail'); document.querySelector('#recordsTitle').textContent = c.name; document.querySelector('#recordsDescription').textContent = `${c.orientation ? 'Registros em colunas' : 'Registros em linhas'} · ${c.records.length} registro(s)`; document.querySelector('#recordsTable').innerHTML = renderRecords(c, c.columns); document.querySelectorAll('[data-edit]').forEach(b => b.onclick = () => showRecordForm(c.records.find(r => r.id === +b.dataset.edit))); document.querySelectorAll('[data-delete-record]').forEach(b => b.onclick = () => deleteRecord(b.dataset.deleteRecord)); document.querySelectorAll('[data-editable-record]').forEach(cell => cell.ondblclick = () => editRecordCell(cell)); }
function renderStructureDetail() { const c = activeCrud; showPage('#structureDetail'); document.querySelector('#structureTitle').textContent = c.name; document.querySelector('#columnsList').innerHTML = c.columns.length ? c.columns.map(col => `<div class="flex items-center justify-between gap-3 rounded-lg border border-line bg-slate-950/30 p-3"><div><b class="text-sm text-white">${escapeHtml(col.name)}</b><p class="mt-1 text-xs text-slate-500">${['Texto', 'Número', 'Seleção'][col.type]}${col.type === 2 ? ` · ${col.options.length} opção(ões)` : ''}</p></div><div class="flex shrink-0 gap-3">${col.type === 2 ? `<button data-column-options="${col.id}" class="text-sm text-emerald-300 hover:text-emerald-200">Opções</button>` : ''}<button data-edit-column="${col.id}" class="text-sm text-violet-300 hover:text-violet-200">Editar</button><button data-delete-column="${col.id}" class="text-sm text-rose-300 hover:text-rose-200">Remover</button></div></div>`).join('') : '<p class="rounded-lg border border-dashed border-line p-4 text-sm text-slate-500">Adicione colunas para começar.</p>'; document.querySelectorAll('[data-delete-column]').forEach(b => b.onclick = () => deleteColumn(b.dataset.deleteColumn)); document.querySelectorAll('[data-edit-column]').forEach(b => b.onclick = () => editColumn(b.dataset.editColumn)); document.querySelectorAll('[data-column-options]').forEach(b => b.onclick = () => columnOptions(b.dataset.columnOptions)); }
async function openCrud(id) { try { activeCrud = (await request(`cruds/${id}/records`)).crud; activeCrud.orientation = +activeCrud.orientation; activeCrud.records ||= []; renderRecordsDetail(); } catch (e) { alert(e.message); } }
async function crudStructure(id) { try { activeCrud = (await request(`cruds/${id}/columns`)).crud; activeCrud.orientation = +activeCrud.orientation; resetColumnForm(); renderStructureDetail(); } catch (e) { alert(e.message); } }
async function columnOptions(columnId) { try { const payload = await request(`columns/${columnId}/options`); activeColumn = payload.column; resetOptionForm(); renderOptionsDetail(); } catch (e) { alert(e.message); } }
async function refreshRecords() { await openCrud(activeCrud.id); await loadCruds(); }
async function refreshStructure() { await crudStructure(activeCrud.id); await loadCruds(); }
async function updateRecordValue(record, column, value) { const values = { ...record.values, [column.id]: value }; await request(`cruds/${activeCrud.id}/records/${record.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ values }) }); record.values = values; }
function editRecordCell(cell) {
  const record = activeCrud.records.find(item => item.id === +cell.dataset.editableRecord), column = activeCrud.columns.find(item => item.id === +cell.dataset.column);
  if (!record || !column || cell.dataset.editing) return;
  const previousValue = record.values[column.id] ?? ''; cell.dataset.editing = 'true';
  if (column.type === 2) {
    cell.innerHTML = recordSelect(column, previousValue); const select = cell.querySelector('select'); select.focus();
    select.onchange = async () => { select.disabled = true; try { await updateRecordValue(record, column, select.value); cell.innerHTML = displayValue(column, select.value); } catch (error) { alert(error.message); cell.innerHTML = displayValue(column, previousValue); } finally { delete cell.dataset.editing; } };
    select.onblur = () => { if (!select.disabled && cell.dataset.editing) { cell.innerHTML = displayValue(column, previousValue); delete cell.dataset.editing; } };
    return;
  }
  const input = document.createElement('input'); input.type = 'text'; input.value = previousValue; input.className = 'input mt-0 min-w-36'; cell.replaceChildren(input); input.focus(); input.select();
  let saved = false, cancelled = false;
  const cancel = () => { if (!saved) { cancelled = true; cell.innerHTML = displayValue(column, previousValue); delete cell.dataset.editing; } };
  const save = async () => { if (saved) return; saved = true; input.disabled = true; try { await updateRecordValue(record, column, input.value); cell.innerHTML = displayValue(column, input.value); } catch (error) { saved = false; input.disabled = false; alert(error.message); input.focus(); } finally { if (saved) delete cell.dataset.editing; } };
  input.onkeydown = event => { if (event.key === 'Enter') { event.preventDefault(); save(); } if (event.key === 'Escape') cancel(); };
  input.onblur = () => { if (!saved && !cancelled) save(); };
}
function showRecordForm(record = null) { const c = activeCrud; document.querySelector('#recordFormTitle').textContent = record ? 'Editar registro' : 'Novo registro'; document.querySelector('#recordForm').innerHTML = c.columns.map(col => `<label class="block text-sm text-slate-300">${escapeHtml(col.name)}${field(col, record?.values[col.id])}</label>`).join('') + `<div class="mt-5 flex justify-end gap-2"><button type="button" id="cancelRecord" class="rounded-lg px-3 py-2 text-sm text-slate-400">Cancelar</button><button class="rounded-lg bg-violet px-4 py-2 text-sm font-semibold text-white">Salvar</button></div>`; const modal = document.querySelector('#recordModal'); modal.classList.replace('hidden', 'flex'); document.querySelector('#cancelRecord').onclick = () => modal.classList.replace('flex', 'hidden'); document.querySelector('#recordForm').onsubmit = async e => { e.preventDefault(); const values = Object.fromEntries([...new FormData(e.target)].map(([k, v]) => [k.replace('value-', ''), v])); try { await request(`cruds/${c.id}/records${record ? `/${record.id}` : ''}`, { method: record ? 'PATCH' : 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ values }) }); modal.classList.replace('flex', 'hidden'); refreshRecords(); } catch (err) { alert(err.message); } }; }
async function deleteRecord(id) { if (confirm('Excluir este registro?')) { try { await request(`cruds/${activeCrud.id}/records/${id}`, { method: 'DELETE' }); refreshRecords(); } catch (e) { alert(e.message); } } }
async function deleteColumn(id) { if (confirm('Remover esta coluna deste CRUD?')) { try { await request(`cruds/${activeCrud.id}/columns/${id}`, { method: 'DELETE' }); refreshStructure(); } catch (e) { alert(e.message); } } }
function editColumn(id) { const column = activeCrud.columns.find(c => c.id === +id); if (!column) return; editingColumnId = column.id; const form = document.querySelector('#columnForm'); form.name.value = column.name; form.type.value = column.type; form.position.value = column.position; document.querySelector('#columnFormTitle').textContent = 'Editar coluna'; document.querySelector('#saveColumn').textContent = 'Salvar alterações'; document.querySelector('#cancelColumnEdit').classList.remove('hidden'); form.scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function resetColumnForm() { editingColumnId = null; const form = document.querySelector('#columnForm'); form.reset(); form.position.value = 0; document.querySelector('#columnFormTitle').textContent = 'Adicionar coluna'; document.querySelector('#saveColumn').textContent = 'Adicionar coluna'; document.querySelector('#cancelColumnEdit').classList.add('hidden'); }
function renderOptionsDetail() { showPage('#optionsDetail'); document.querySelector('#optionsTitle').textContent = activeColumn.name; document.querySelector('#optionsList').innerHTML = activeColumn.options.length ? activeColumn.options.map(option => `<div class="flex items-center justify-between gap-3 rounded-lg border border-line bg-slate-950/30 p-3"><div><b class="text-sm text-white">${escapeHtml(option.value)}</b><p class="mt-1 text-xs text-slate-500">Ordem: ${option.position}</p></div><div class="flex shrink-0 gap-3"><button data-edit-option="${option.id}" class="text-sm text-violet-300 hover:text-violet-200">Editar</button><button data-delete-option="${option.id}" class="text-sm text-rose-300 hover:text-rose-200">Remover</button></div></div>`).join('') : '<p class="rounded-lg border border-dashed border-line p-4 text-sm text-slate-500">Adicione opções para começar.</p>'; document.querySelectorAll('[data-edit-option]').forEach(b => b.onclick = () => editOption(b.dataset.editOption)); document.querySelectorAll('[data-delete-option]').forEach(b => b.onclick = () => deleteOption(b.dataset.deleteOption)); }
function editOption(id) { const option = activeColumn.options.find(o => o.id === +id); if (!option) return; editingOptionId = option.id; const form = document.querySelector('#optionForm'); form.elements.value.value = option.value; form.elements.position.value = option.position; document.querySelector('#optionFormTitle').textContent = 'Editar opção'; document.querySelector('#saveOption').textContent = 'Salvar alterações'; document.querySelector('#cancelOptionEdit').classList.remove('hidden'); }
function resetOptionForm() { editingOptionId = null; const form = document.querySelector('#optionForm'); form.reset(); form.position.value = 0; document.querySelector('#optionFormTitle').textContent = 'Adicionar opção'; document.querySelector('#saveOption').textContent = 'Adicionar opção'; document.querySelector('#cancelOptionEdit').classList.add('hidden'); }
function backToDashboard() { document.querySelector('#recordsDetail').classList.add('hidden'); document.querySelector('#structureDetail').classList.add('hidden'); document.querySelector('#optionsDetail').classList.add('hidden'); document.querySelector('#dashboard').classList.remove('hidden'); loadCruds(); }

const modal = document.querySelector('#modal'); const showModal = () => modal.classList.replace('hidden', 'flex'); const hideModal = () => modal.classList.replace('flex', 'hidden'); document.querySelector('#newCrud').onclick = showModal; document.querySelector('#closeModal').onclick = hideModal; document.querySelector('#cancel').onclick = hideModal;
document.querySelector('#crudForm').onsubmit = async e => { e.preventDefault(); try { const name = document.querySelector('#crudName').value.trim(), orientation = +document.querySelector('input[name="orientation"]:checked').value; if (!name) return; await request('cruds', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, orientation }) }); hideModal(); e.target.reset(); loadCruds(); } catch (err) { alert(err.message); } };
document.querySelector('#backToDashboard').onclick = backToDashboard; document.querySelectorAll('.backToDashboard').forEach(button => button.onclick = backToDashboard); document.querySelector('#newRecord').onclick = () => showRecordForm(); document.querySelector('#openStructureFromRecords').onclick = () => crudStructure(activeCrud.id); document.querySelector('#openRecordsFromStructure').onclick = () => openCrud(activeCrud.id); document.querySelector('#backToStructure').onclick = () => crudStructure(activeCrud.id); document.querySelector('#cancelColumnEdit').onclick = resetColumnForm; document.querySelector('#cancelOptionEdit').onclick = resetOptionForm;
document.querySelector('#columnForm').onsubmit = async e => { e.preventDefault(); const data = new FormData(e.target), type = +data.get('type'); const url = `cruds/${activeCrud.id}/columns${editingColumnId ? `/${editingColumnId}` : ''}`; try { await request(url, { method: editingColumnId ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: data.get('name'), type, position: +data.get('position') }) }); resetColumnForm(); refreshStructure(); } catch (err) { alert(err.message); } };
document.querySelector('#optionForm').onsubmit = async e => { e.preventDefault(); const data = new FormData(e.target); const url = `columns/${activeColumn.id}/options${editingOptionId ? `/${editingOptionId}` : ''}`; try { await request(url, { method: editingOptionId ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ value: data.get('value'), position: +data.get('position') }) }); await columnOptions(activeColumn.id); } catch (err) { alert(err.message); } };
async function deleteOption(id) { if (confirm('Remover esta opção?')) { try { await request(`columns/${activeColumn.id}/options/${id}`, { method: 'DELETE' }); await columnOptions(activeColumn.id); } catch (e) { alert(e.message); } } }
document.querySelector('#search').oninput = e => render(cruds.filter(c => c.name.toLowerCase().includes(e.target.value.toLowerCase())));
loadCruds();
